[package]
name = "encrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
ring = { version = "0.17.11" }
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }
serde = { version = "1.0.218", features = ["derive"] }


[dev-dependencies]
thiserror = { version = "2.0.11" }
